# Generated by Django 5.2.4 on 2025-07-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booknook', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_condition',
            field=models.CharField(choices=[('new', 'New'), ('used_like_new', 'Used - Like New'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair'), ('used_poor', 'Used - Poor')], default='used_good', help_text='Condition of the book', max_length=15),
        ),
    ]
