# Generated by Django 5.2.4 on 2025-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booknook', '0004_alter_post_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exchange_with',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
